apiVersion: v1
kind: Service
metadata:
  name: survey-service
spec:
  selector:
    app: survey
  type: LoadBalancer  # Expose service externally
  ports:
    - protocol: TCP
      port: 80  # Port exposed externally
      targetPort: 80  # Port on the container
 
